project:
  type: website

website:
  title: "Home"
  site-url: https://evangeliaberdou.github.io/
  open-graph: true
  page-footer: "Made with ❤️ and Quarto"

  navbar:
    title: Evangelia Berdou
    right:
      - text: Blog
        icon: lightning-charge-fill
        href: blog/index.qmd

format:
  html:
    linkcolor: "#D65211"
    mainfont: "Aptos Sans"
    fontsize: 15px
    theme: [flatly, styles.scss]

