project:
  type: website

website:
  title: "Home"
  site-url: https://evangeliaberdou.github.io/
  open-graph: true
  page-footer: "Made with ❤️ and Quarto"

  navbar:
    title: Evangelia Berdou
    left:
      - text: Blog
        icon: lightning-charge-fill
        href: blog/index.qmd
    tools:
      - icon: linkedin
        href: https://linkedin.com/in/evangeliaberdou
      - icon: download
        text: Download CV
        href: Berdou_CV.pdf
      - icon: kanban
        text: Power BI

format:
  html:
    linkcolor: "#D65211"
    mainfont: "Aptos Sans"
    fontsize: 15px
    theme: [flatly, styles.scss]

